haiti_insights:
  outputs:
    dev:
      dataset: haiti_idp_dataset
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: C:\Users\young\AppData\Roaming\gcloud\haiti-insights-c832f2d05399.json
      location: us-east4
      method: service-account
      priority: interactive
      project: haiti-insights
      threads: 1
      type: bigquery
  target: dev
